package app.gui.enums;

public enum ActionCommand {
    ADD_SHAPE_RECTANGLE,
    ADD_SHAPE_TRIANGLE,
    ADD_SHAPE_CIRCLE,
    ADD_SHAPE_TEST,
    SAVE_FILE,
    LOAD_FILE,
    CHOOSE_COLOR,
    EXPORT_IMAGE,
    DELETE_SHAPE,
    SHAPE_CHANGE_VALUE,
    SAVE_GROUP,
    DELETE_GROUP
}
